# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 00:19
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_auto_20150615_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='img',
            field=models.ImageField(default=datetime.datetime(2016, 4, 7, 0, 19, 13, 81108, tzinfo=utc), upload_to=django.core.files.storage.FileSystemStorage(location='static/2016/04')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static/2016/04'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='static/2016/04'), upload_to=''),
        ),
    ]
