# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 00:32
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_auto_20160407_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static/2016/04'), upload_to=''),
        ),
    ]
