# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_auto_20160407_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
