# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 22:33
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_auto_20160430_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='static/2016/08'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static/2016/08'), upload_to=''),
        ),
    ]
