# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0013_auto_20160808_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='fecha_psql',
        ),
    ]
